---
title: "psych710_final"
output: html_document
date: "2024-04-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Background/Hypothesis
The dataset that we have chosen to use is from Sparkman et al. 2022 article, "Americans experience a false social reality by underestimating popular climate policy support by nearly half." Our research question is How do socioeconomic factors predict green policy ideologies? The data that we have comes from a survey census (Ipsos eNation Omnibus) that utilizes questions for misperception for others' thoughts and behaviors by concerning climate change and support for mitigation policies, comparing with the ground truth of support of climate policies (from Yale's program on Climate Change Communication). The outcome variable, levels of support/more concern for climate policies, were measured twice with different wording. Overall, we predict that individuals' socioeconomic statuses will affect the tendency of changing levels of support/more concern for climate policies. 

## Proposed Analysis
For sure, we will be using an lmer model to predict climate policy support from socioeconomic factors which takes into account the repeated measures between the two climate change/policy-related questions with different wording that these surveys were sent out. In our analysis, we will create two composite scores of climate policy support and take the difference (pluralistic ignorance) to use as our outcome variable and then use education level (USEDU3), housing status (USHOU1), and marital status (USMAR2) as our predictors. (We may also want to include employment (EMP01), but this may add too much complexity?).

lmer model: lmer(green_m ~ edu + housing + marital + (1|id) + (1|wave)*)

Tentatively, we also want to look at using a bayes regression model with the same setup as in our lmer setup. *Also, we are unsure whether to include the random effects of the wave variable.
