---
title: "psych710_final"
output: html_document
date: "2024-04-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(tidyverse)
library(lme4)
library(car)
library(ggplot2)
library(effects)
library(psych)
library(emmeans)
library(ggeffects)
library(bridgesampling)
library(bayestestR)
library(bayesplot)
library(rstanarm)
library(rstantools)
```
# Data Analysis

##Read data, generate composite scores
```{r}
d = read.csv('full_dataset.csv') #Read data

#Generate an id variable
d = tibble::rowid_to_column(d, "id")
```

##Clean data: 
>>Household income(USHHI2, I guess the codebook put it wrong)
>>Education level(USEDU3)

```{r}
#Transform to long format
d_self = d %>% select(id, USHHI2, USEDU3, 
                       GRID_GTS1_1_GTS1 , GRID_GTS1_2_GTS1, GRID_GTS1_3_GTS1, 
                       GRID_GTS1_4_GTS1, GRID_GTS1_5_GTS1)
d_society = d %>% select(id, USHHI2, USEDU3,
                       GRID_GTS2_1_GTS2, GRID_GTS2_2_GTS2, GRID_GTS2_3_GTS2, 
                       GRID_GTS2_4_GTS2, GRID_GTS2_5_GTS2)
dl_self <- d_self %>% as.data.table() %>% data.table::melt(
  measure.vars =
    list(c('GRID_GTS1_1_GTS1', 'GRID_GTS1_2_GTS1', 'GRID_GTS1_3_GTS1', 
    'GRID_GTS1_4_GTS1', 'GRID_GTS1_5_GTS1')), 
  variable.name = "trial_name", 
  value.name = "climate_tend"
  ) %>% 
  arrange(id) %>% as.data.frame()
dl_society <- d_society %>% as.data.table() %>% data.table::melt(
  measure.vars =
    list(c('GRID_GTS2_1_GTS2', 'GRID_GTS2_2_GTS2', 'GRID_GTS2_3_GTS2', 
    'GRID_GTS2_4_GTS2', 'GRID_GTS2_5_GTS2')), 
  variable.name = "trial_name", 
  value.name = "climate_tend"
  ) %>% 
  arrange(id) %>% as.data.frame()

#Recode trial_name
dl_self$trial_num = dplyr::recode(dl_self$trial_name, 
                             "GRID_GTS1_1_GTS1" = 1, 
                             "GRID_GTS1_2_GTS1" = 2,
                             "GRID_GTS1_3_GTS1" = 3,
                             "GRID_GTS1_4_GTS1" = 4,
                             "GRID_GTS1_5_GTS1" = 5)

dl_society$trial_num = dplyr::recode(dl_society$trial_name, 
                             "GRID_GTS2_1_GTS2" = 1, 
                             "GRID_GTS2_2_GTS2" = 2,
                             "GRID_GTS2_3_GTS2" = 3,
                             "GRID_GTS2_4_GTS2" = 4,
                             "GRID_GTS2_5_GTS2" = 5)
```

##Fit a mixed effect model
```{r}
dl_self_test = dl_self[1: 100,] #This datafrmae is just for testing the code
dl_society_test = dl_society[1: 100,] #This datafrmae is just for testing the code
m_self = stan_lmer(climate_tend ~ USHHI2 * USEDU3 + 
                     (1|id) + (1 + USHHI2 * USEDU3|trial_num), data = dl_self_test, 
               prior_intercept = normal(39, 3),
               prior = normal(0, 7), 
               chain = 5, iter = 5000)
summary(m_self)

m_society = stan_lmer(climate_tend ~ USHHI2 * USEDU3 + 
                        (1|id) + (1 + USHHI2 * USEDU3|trial_num), 
                      data = dl_society_test, 
               prior_intercept = normal(42, 25),
               prior = normal(0, 7), 
               chain = 5, iter = 5000)
summary(m_society)
```

##Fit a mixed effect model
```{r}
dl_self_test = dl_self[1: 100,] #This datafrmae is just for testing the code
dl_society_test = dl_society[1: 100,] #This datafrmae is just for testing the code
m_self = lmer(climate_tend ~ USHHI2 * USEDU3 + 
                     (1|id) + (1 + USHHI2 * USEDU3|trial_num), data = dl_self_test)
anova(m_self, type = 3, )
summary(m_self)

m_society = stan_lmer(climate_tend ~ USHHI2 * USEDU3 + 
                        (1|id) + (1 + USHHI2 * USEDU3|trial_num), 
                      data = dl_society_test, 
               prior_intercept = normal(75, 46),
               prior = normal(-7, 5), 
               chain = 5, iter = 5000)
summary(m_society)

equivalence_test(m_society, range = c(-.01, .01), ci = .90)
```

